const immunizationSchedules = {
  INDIA: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1 of 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 0,
      months: 0,
    },

    {
      age: "At Birth",
      vaccine: "BCG - Dose 1",
      protection: "Bacillus Calmette–Guerin (Protection against tuberculosis)",
      weeks: 0,
      months: 0,
    },

    {
      age: "At Birth",
      vaccine: "OPV - Dose 1 of 4",
      protection: "Oral Polio Vaccine",
      weeks: 0,
      months: 0,
    },

    {
      age: "6 weeks",
      vaccine: "Hepatitis B - Dose 2 of 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 6,
      months: 0,
    },

    {
      age: "6 weeks",
      vaccine: "DTaP - Dose 1 of 5",
      protection: "	Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 6,
      months: 0,
    },

    {
      age: "6 weeks",
      vaccine: "IPV - Dose 1 of 4",
      protection: "Polio",
      weeks: 6,
      months: 0,
    },

    {
      age: "6 weeks",
      vaccine: "Hib - Dose 1 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 6,
      months: 0,
    },

    {
      age: "6 weeks",
      vaccine: "Rotavirus - Dose 1 of 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 6,
      months: 0,
    },
    {
      age: "6 weeks",
      vaccine: "Rotavirus - Dose 1 of 3",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 6,
      months: 0,
    },

    {
      age: "10 weeks",
      vaccine: "DTaP - Dose 2 of 5",
      protection: "	Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 10,
      months: 0,
    },
    {
      age: "10 weeks",
      vaccine: "Hib - Dose 2 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 10,
      months: 0,
    },
    {
      age: "10 weeks",
      vaccine: "IPV - Dose 2 of 4",
      protection: "Polio",
      weeks: 10,
      months: 0,
    },
    {
      age: "10 weeks",
      vaccine: "	PCV - Dose 2 of 4",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 10,
      months: 0,
    },
    {
      age: "10 weeks",
      vaccine: "	Rotavirus ** - Dose 2 of 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 10,
      months: 0,
    },

    {
      age: "14 weeks",
      vaccine: "DTaP - Dose 3 of 5",
      protection: "	Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 14,
      months: 0,
    },
    {
      age: "14 weeks",
      vaccine: "Hib - Dose 3 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 14,
      months: 0,
    },
    {
      age: "14 weeks",
      vaccine: "IPV - Dose 3 of 4",
      protection: "Polio",
      weeks: 14,
      months: 0,
    },
    {
      age: "14 weeks",
      vaccine: "	PCV - Dose 3 of 4",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 14,
      months: 0,
    },
    {
      age: "14 weeks",
      vaccine: "	Rotavirus ** - Dose 3 of 3",
      protection: "	Oral Polio Vaccine",
      weeks: 14,
      months: 0,
    },
    {
      age: "6 months",
      vaccine: "	OPV - Dose 2 of 4",
      protection: "Hepatitis B virus",
      weeks: 0,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "	Hepatitis B - Dose 3 of 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 0,
      months: 6,
    },


    {
      age: "9 months",
      vaccine: "	OPV - Dose 3 of 4",
      protection: "Oral Polio Vaccine",
      weeks: 0,
      months: 9,
    },
    {
      age: "9 months",
      vaccine: "	MMR - Dose 1 of 3",
      protection: "Measles, mumps, and rubella (German measles)",
      weeks: 0,
      months: 9,
    },

    {
      age: "9 to 12 months",
      vaccine: "TCVs - Dose 1 of 2",
      protection: "	Typhoid Conjugate Vaccine",
      weeks: 0,
      months: 12,
    },
    {
      age: "15 months",
      vaccine: "MMR - Dose 2 of 2",
      protection: "Measles, Mumps, Rubella",
      weeks: 0,
      months: 15,
    },
    {
      age: "18 months",
      vaccine: "DTaP - Dose 4 of 5",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 18,
    },
    {
      age: "4-6 years",
      vaccine: "DTaP - Dose 5 of 5",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "10-12 years",
      vaccine: "Tdap - Dose 1",
      protection: "Tetanus, Diphtheria, Pertussis",
      weeks: 0,
      months: 120,
      rangeMonths: 144,
    },
    {
      age: "10-12 years",
      vaccine: "HPV - Dose 1",
      protection: "Human Papillomavirus",
      weeks: 0,
      months: 120,
      rangeMonths: 144,
    },
  ],
  USA: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1 of 3",
      protection: "Hepatitis B virus",
      weeks: 0,
      months: 0,
    },
    {
      age: "1-2 months",
      vaccine: "Hepatitis B - Dose 2 of 3",
      protection: "Hepatitis B virus",
      weeks: 0,
      months: 1,
    },
    {
      age: "2 months",
      vaccine: "DTaP - Dose 1 of 5",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "IPV - Dose 1 of 4",
      protection: "Polio",
      weeks: 0,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "PCV13 - Dose 1 of 4",
      protection: "Pneumococcal disease",
      weeks: 0,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "RV - Dose 1 of 3",
      protection: "Rotavirus",
      weeks: 0,
      months: 2,
    },
    {
      age: "4 months",
      vaccine: "DTaP - Dose 2 of 5",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "IPV - Dose 2 of 4",
      protection: "Polio",
      weeks: 0,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "PCV13 - Dose 2 of 4",
      protection: "Pneumococcal disease",
      weeks: 0,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "RV - Dose 2 of 3",
      protection: "Rotavirus",
      weeks: 0,
      months: 4,
    },
    {
      age: "6 months",
      vaccine: "DTaP - Dose 3 of 5",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "PCV13 - Dose 3 of 4",
      protection: "Pneumococcal disease",
      weeks: 0,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "RV - Dose 3 of 3",
      protection: "Rotavirus",
      weeks: 0,
      months: 6,
    },
    {
      age: "6-18 months",
      vaccine: "IPV - Dose 3 of 4",
      protection: "Polio",
      weeks: 0,
      months: 6,
      rangeMonths: 18,
    },
    {
      age: "6-18 months",
      vaccine: "Hepatitis B - Dose 3 of 3",
      protection: "Hepatitis B virus",
      weeks: 0,
      months: 6,
      rangeMonths: 18,
    },
    {
      age: "12-15 months",
      vaccine: "MMR - Dose 1 of 2",
      protection: "Measles, Mumps, Rubella",
      weeks: 0,
      months: 12,
      rangeMonths: 15,
    },
    {
      age: "12-15 months",
      vaccine: "Varicella - Dose 1 of 2",
      protection: "Chickenpox",
      weeks: 0,
      months: 12,
      rangeMonths: 15,
    },
    {
      age: "12-15 months",
      vaccine: "PCV13 - Dose 4 of 4",
      protection: "Pneumococcal disease",
      weeks: 0,
      months: 12,
      rangeMonths: 15,
    },
    {
      age: "12-18 months",
      vaccine: "Hib - Dose 4 of 4",
      protection: "Haemophilus influenzae type b",
      weeks: 0,
      months: 12,
      rangeMonths: 18,
    },
    {
      age: "4-6 years",
      vaccine: "DTaP - Dose 5 of 5",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4-6 years",
      vaccine: "IPV - Dose 4 of 4",
      protection: "Polio",
      weeks: 0,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4-6 years",
      vaccine: "MMR - Dose 2 of 2",
      protection: "Measles, Mumps, Rubella",
      weeks: 0,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4-6 years",
      vaccine: "Varicella - Dose 2 of 2",
      protection: "Chickenpox",
      weeks: 0,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "11-12 years",
      vaccine: "Tdap - Dose 1",
      protection: "Tetanus, Diphtheria, Pertussis",
      weeks: 0,
      months: 132,
      rangeMonths: 144,
    },
    {
      age: "11-12 years",
      vaccine: "HPV - Dose 1",
      protection: "Human Papillomavirus",
      weeks: 0,
      months: 132,
      rangeMonths: 144,
    },
  ],
  UK: [
    {
      age: "8 weeks",
      vaccine: "6-in-1 - Dose 1 of 3",
      protection: "Diphtheria, Tetanus, Pertussis, Polio, Hib, Hepatitis B",
      weeks: 8,
      months: 0,
    },
    {
      age: "8 weeks",
      vaccine: "Rotavirus - Dose 1 of 2",
      protection: "Rotavirus",
      weeks: 8,
      months: 0,
    },
    {
      age: "8 weeks",
      vaccine: "MenB - Dose 1 of 3",
      protection: "Meningococcal B",
      weeks: 8,
      months: 0,
    },
    {
      age: "12 weeks",
      vaccine: "6-in-1 - Dose 2 of 3",
      protection: "Diphtheria, Tetanus, Pertussis, Polio, Hib, Hepatitis B",
      weeks: 12,
      months: 0,
    },
    {
      age: "12 weeks",
      vaccine: "Rotavirus - Dose 2 of 2",
      protection: "Rotavirus",
      weeks: 12,
      months: 0,
    },
    {
      age: "16 weeks",
      vaccine: "6-in-1 - Dose 3 of 3",
      protection: "Diphtheria, Tetanus, Pertussis, Polio, Hib, Hepatitis B",
      weeks: 16,
      months: 0,
    },
    {
      age: "16 weeks",
      vaccine: "MenB - Dose 2 of 3",
      protection: "Meningococcal B",
      weeks: 16,
      months: 0,
    },
    {
      age: "12 months",
      vaccine: "Hib/MenC - Dose 1",
      protection: "Haemophilus influenzae type b, Meningococcal C",
      weeks: 0,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "MMR - Dose 1 of 2",
      protection: "Measles, Mumps, Rubella",
      weeks: 0,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "MenB - Dose 3 of 3",
      protection: "Meningococcal B",
      weeks: 0,
      months: 12,
    },
    {
      age: "3 years 4 months",
      vaccine: "4-in-1 - Preschool Booster",
      protection: "Diphtheria, Tetanus, Pertussis, Polio",
      weeks: 0,
      months: 40,
    },
    {
      age: "3 years 4 months",
      vaccine: "MMR - Dose 2 of 2",
      protection: "Measles, Mumps, Rubella",
      weeks: 0,
      months: 40,
    },
    {
      age: "12-13 years",
      vaccine: "HPV - Dose 1",
      protection: "Human Papillomavirus",
      weeks: 0,
      months: 144,
      rangeMonths: 156,
    },
    {
      age: "14 years",
      vaccine: "3-in-1 - Teenage Booster",
      protection: "Tetanus, Diphtheria, Polio",
      weeks: 0,
      months: 168,
    },
    {
      age: "14 years",
      vaccine: "MenACWY - Dose 1",
      protection: "Meningococcal A, C, W, Y",
      weeks: 0,
      months: 168,
    },
  ],
  CANADA: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1 of 3",
      protection: "Hepatitis B virus",
      weeks: 0,
      months: 0,
    },
    {
      age: "2 months",
      vaccine: "DTaP - Dose 1 of 5",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "IPV - Dose 1 of 4",
      protection: "Polio",
      weeks: 0,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Hib - Dose 1 of 4",
      protection: "Haemophilus influenzae type b",
      weeks: 0,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "PCV13 - Dose 1 of 4",
      protection: "Pneumococcal disease",
      weeks: 0,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Rotavirus - Dose 1 of 3",
      protection: "Rotavirus",
      weeks: 0,
      months: 2,
    },
    {
      age: "4 months",
      vaccine: "DTaP - Dose 2 of 5",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "IPV - Dose 2 of 4",
      protection: "Polio",
      weeks: 0,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Hib - Dose 2 of 4",
      protection: "Haemophilus influenzae type b",
      weeks: 0,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "PCV13 - Dose 2 of 4",
      protection: "Pneumococcal disease",
      weeks: 0,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Rotavirus - Dose 2 of 3",
      protection: "Rotavirus",
      weeks: 0,
      months: 4,
    },
    {
      age: "6 months",
      vaccine: "DTaP - Dose 3 of 5",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Hib - Dose 3 of 4",
      protection: "Haemophilus influenzae type b",
      weeks: 0,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "PCV13 - Dose 3 of 4",
      protection: "Pneumococcal disease",
      weeks: 0,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Rotavirus - Dose 3 of 3",
      protection: "Rotavirus",
      weeks: 0,
      months: 6,
    },
    {
      age: "12 months",
      vaccine: "MMR - Dose 1 of 2",
      protection: "Measles, Mumps, Rubella",
      weeks: 0,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "Varicella - Dose 1 of 2",
      protection: "Chickenpox",
      weeks: 0,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "Hib - Dose 4 of 4",
      protection: "Haemophilus influenzae type b",
      weeks: 0,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "PCV13 - Dose 4 of 4",
      protection: "Pneumococcal disease",
      weeks: 0,
      months: 12,
    },
    {
      age: "18 months",
      vaccine: "DTaP - Dose 4 of 5",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "IPV - Dose 3 of 4",
      protection: "Polio",
      weeks: 0,
      months: 18,
    },
    {
      age: "4-6 years",
      vaccine: "DTaP - Dose 5 of 5",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4-6 years",
      vaccine: "IPV - Dose 4 of 4",
      protection: "Polio",
      weeks: 0,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4-6 years",
      vaccine: "MMR - Dose 2 of 2",
      protection: "Measles, Mumps, Rubella",
      weeks: 0,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4-6 years",
      vaccine: "Varicella - Dose 2 of 2",
      protection: "Chickenpox",
      weeks: 0,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "9-10 years",
      vaccine: "HPV - Dose 1",
      protection: "Human Papillomavirus",
      weeks: 0,
      months: 108,
      rangeMonths: 120,
    },
    {
      age: "14-16 years",
      vaccine: "Tdap - Dose 1",
      protection: "Tetanus, Diphtheria, Pertussis",
      weeks: 0,
      months: 168,
      rangeMonths: 192,
    },
  ],
  AUSTRALIA: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1 of 3",
      protection: "Hepatitis B virus",
      weeks: 0,
      months: 0,
    },
    {
      age: "2 months",
      vaccine: "6-in-1 - Dose 1 of 3",
      protection: "Diphtheria, Tetanus, Pertussis, Polio, Hib, Hepatitis B",
      weeks: 0,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "PCV13 - Dose 1 of 3",
      protection: "Pneumococcal disease",
      weeks: 0,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Rotavirus - Dose 1 of 2",
      protection: "Rotavirus",
      weeks: 0,
      months: 2,
    },
    {
      age: "4 months",
      vaccine: "6-in-1 - Dose 2 of 3",
      protection: "Diphtheria, Tetanus, Pertussis, Polio, Hib, Hepatitis B",
      weeks: 0,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "PCV13 - Dose 2 of 3",
      protection: "Pneumococcal disease",
      weeks: 0,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Rotavirus - Dose 2 of 2",
      protection: "Rotavirus",
      weeks: 0,
      months: 4,
    },
    {
      age: "6 months",
      vaccine: "6-in-1 - Dose 3 of 3",
      protection: "Diphtheria, Tetanus, Pertussis, Polio, Hib, Hepatitis B",
      weeks: 0,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "PCV13 - Dose 3 of 3",
      protection: "Pneumococcal disease",
      weeks: 0,
      months: 6,
    },
    {
      age: "12 months",
      vaccine: "MMR - Dose 1 of 2",
      protection: "Measles, Mumps, Rubella",
      weeks: 0,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "MenACWY - Dose 1",
      protection: "Meningococcal A, C, W, Y",
      weeks: 0,
      months: 12,
    },
    {
      age: "18 months",
      vaccine: "MMR - Dose 2 of 2",
      protection: "Measles, Mumps, Rubella",
      weeks: 0,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "DTaP - Booster",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 18,
    },
    {
      age: "4 years",
      vaccine: "4-in-1 - Booster",
      protection: "Diphtheria, Tetanus, Pertussis, Polio",
      weeks: 0,
      months: 48,
    },
    {
      age: "12-13 years",
      vaccine: "HPV - Dose 1",
      protection: "Human Papillomavirus",
      weeks: 0,
      months: 144,
      rangeMonths: 156,
    },
    {
      age: "14-16 years",
      vaccine: "dTpa - Booster",
      protection: "Diphtheria, Tetanus, Pertussis",
      weeks: 0,
      months: 168,
      rangeMonths: 192,
    },
    {
      age: "14-16 years",
      vaccine: "MenACWY - Booster",
      protection: "Meningococcal A, C, W, Y",
      weeks: 0,
      months: 168,
      rangeMonths: 192,
    },
  ],
};

export default immunizationSchedules;
