const immunizationSchedules = {
  INDIA: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1 of 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 0,
      months: 0,
    },
    {
      age: "At Birth",
      vaccine: "BCG - Dose 1",
      protection: "Bacillus Calmette–Guerin (Protection against tuberculosis)",
      weeks: 0,
      months: 0,
    },
    {
      age: "At Birth",
      vaccine: "OPV - Dose 1 of 4",
      protection: "Oral Polio Vaccine",
      weeks: 0,
      months: 0,
    },
    {
      age: "6 weeks",
      vaccine: "Hepatitis B - Dose 2 of 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 weeks",
      vaccine: "DTaP - Dose 1 of 5",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 weeks",
      vaccine: "IPV - Dose 1 of 4",
      protection: "Polio",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 weeks",
      vaccine: "Hib - Dose 1 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 weeks",
      vaccine: "Rotavirus - Dose 1 of 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 weeks",
      vaccine: "PCV - Dose 1 of 4",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "10 weeks",
      vaccine: "DTaP - Dose 2 of 5",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 10,
      months: 2.5,
    },
    {
      age: "10 weeks",
      vaccine: "Hib - Dose 2 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 10,
      months: 2.5,
    },
    {
      age: "10 weeks",
      vaccine: "IPV - Dose 2 of 4",
      protection: "Polio",
      weeks: 10,
      months: 2.5,
    },
    {
      age: "10 weeks",
      vaccine: "PCV - Dose 2 of 4",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 10,
      months: 2.5,
    },
    {
      age: "10 weeks",
      vaccine: "Rotavirus - Dose 2 of 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 10,
      months: 2.5,
    },
    {
      age: "14 weeks",
      vacc极: "DTaP - Dose 3 of 5",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "14 weeks",
      vaccine: "Hib - Dose 3 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "14 weeks",
      vaccine: "IPV - Dose 3 of 4",
      protection: "Polio",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "14 weeks",
      vaccine: "PCV - Dose 3 of 4",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "14 weeks",
      vaccine: "Rotavirus - Dose 3 of 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "6 months",
      vaccine: "OPV - Dose 2 of 4",
      protection: "Oral Polio Vaccine",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Hepatitis B - Dose 3 of 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 26,
      months: 6,
    },
    {
      age: "9 months",
      vaccine: "OPV - Dose 3 of 4",
      protection: "Oral Polio Vaccine",
      weeks: 39,
      months: 9,
    },
    {
      age: "9 months",
      vaccine: "MMR - Dose 1 of 3",
      protection: "Measles, mumps, and rubella (German measles)",
      weeks: 39,
      months: 9,
    },
    {
      age: "9 to 12 months",
      vaccine: "TCVs - Dose 1 of 2",
      protection: "Typhoid Conjugate Vaccine",
      weeks: 39,
      months: 9,
      rangeMonths: 12,
    },
    {
      age: "12 months",
      vaccine: "Hepatitis A - Dose 1 of 2",
      protection: "Hepatitis A virus (inflammation of the liver)",
      weeks: 52,
      months: 12,
    },
    {
      age: "15 months",
      vaccine: "MMR - Dose 2 of 3",
      protection: "Measles, mumps, and rubella (German measles)",
      weeks: 65,
      months: 15,
    },
    {
      age: "15 months",
      vaccine: "Varicella - Dose 1 of 2",
      protection: "Chickenpox",
      weeks: 65,
      months: 15,
    },
    {
      age: "15 months",
      vaccine: "PCV Booster - Dose 4 of 4",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 65,
      months: 15,
    },
    {
      age: "16 to 18 months",
      vaccine: "DTwP B2/DTaP B1 - Dose 4 of 5",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 70,
      months: 16,
      rangeMonths: 18,
    },
    {
      age: "16 to 18 months",
      vaccine: "IPV - Dose 4 of 4",
      protection: "Polio",
      weeks: 70,
      months: 16,
      rangeMonths: 18,
    },
    {
      age: "16 to 18 months",
      vaccine: "Hib - Dose 4 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 70,
      months: 16,
      rangeMonths: 18,
    },
    {
      age: "18 months",
      vaccine: "Hepatitis A - Dose 2 of 2",
      protection: "Hepatitis A virus (inflammation of the liver)",
      weeks: 78,
      months: 18,
    },
    {
      age: "24 months",
      vaccine: "TCVs - Dose 2 of 2",
      protection: "Typhoid Conjugate Vaccine",
      weeks: 104,
      months: 24,
    },
    {
      age: "4 to 6 years",
      vaccine: "DTwP B2/DTaP B1 - Dose 5 of 5",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 208,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4 to 6 years",
      vaccine: "OPV - Dose 4 of 4",
      protection: "Oral Polio Vaccine",
      weeks: 208,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4 to 6 years",
      vaccine: "Varicella - Dose 2 of 2",
      protection: "Chickenpox",
      weeks: 208,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4 to 6 years",
      vaccine: "MMR - Dose 3 of 3",
      protection: "Measles, mumps, and rubella (German measles)",
      weeks: 208,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "10 to 12 years",
      vaccine: "Tdap - Dose 1",
      protection: "Tetanus, diphtheria, and pertussis",
      weeks: 520,
      months: 120,
      rangeMonths: 144,
    },
    {
      age: "10 to 12 years",
      vaccine: "HPV - Dose 1",
      protection: "Human Papillomavirus",
      weeks: 520,
      months: 120,
      rangeMonths: 144,
    },
  ],

  USA: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1 of 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 0,
      months: 0,
    },
    {
      age: "1 to 2 months",
      vaccine: "Hepatitis B - Dose 2 of 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 4,
      months: 1,
      rangeMonths: 2,
    },
    {
      age: "2 months",
      vaccine: "DTaP - Dose 1 of 5",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Hib - Dose 1 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vacc极: "Polio (IPV) - Dose 1 of 4",
      protection: "Polio",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Pneumococcal conjugate (PCV13) - Dose 1 of 4",
      protection:
        "Infections of the blood, brain, joints, inner ears, or lungs (pneumonia)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Rotavirus - Dose 1 of 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 8,
      months: 2,
    },
    {
      age: "4 months",
      vaccine: "DTaP - Dose 2 of 5",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Hib - Dose 2 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Polio (IPV) - Dose 2 of 4",
      protection: "Polio",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Pneumococcal conjugate (PCV13) - Dose 2 of 4",
      protection:
        "Infections of the blood, brain, joints, inner ears, or lungs (pneumonia)",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Rotavirus - Dose 2 of 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 17,
      months: 4,
    },
    {
      age: "6 months",
      vaccine: "DTaP - Dose 3 of 5",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Hib - Dose 3 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Pneumococcal conjugate (PCV13) - Dose 3 of 4",
      protection:
        "Infections of the blood, brain, joints, inner ears, or lungs (pneumonia)",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Rotavirus - Dose 3 of 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 to 18 months",
      vaccine: "Hepatitis B - Dose 3 of 3",
      protection:
        "Hepatitis B (chronic inflammation of the liver, life-long complications)",
      weeks: 26,
      months: 6,
      rangeMonths: 18,
    },
    {
      age: "6 to 18 months",
      vaccine: "Polio (IPV) - Dose 3 of 4",
      protection: "Polio",
      weeks: 26,
      months: 6,
      rangeMonths: 18,
    },
    {
      age: "6 months or older",
      vaccine: "Influenza - Dose 1 of 2 (Annual)",
      protection: "Flu and complications",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months or older",
      vaccine: "Influenza - Dose 2 of 2 (Annual)",
      protection: "Flu and complications",
      weeks: 26,
      months: 6,
      note: "Second dose given 4 weeks after first dose for initial vaccination",
    },
    {
      age: "12 to 15 months",
      vaccine: "Hib - Dose 4 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 52,
      months: 12,
      rangeMonths: 15,
    },
    {
      age: "12 to 15 months",
      vaccine: "Pneumococcal conjugate (PCV13) - Dose 4 of 4",
      protection:
        "Infections of the blood, brain, joints, inner ears, or lungs (pneumonia)",
      weeks: 52,
      months: 12,
      rangeMonths: 15,
    },
    {
      age: "12 to 15 months",
      vaccine: "MMR - Dose 1 of 2",
      protection: "Measles, mumps, and rubella (German measles)",
      weeks: 52,
      months: 12,
      rangeMonths: 15,
    },
    {
      age: "12 to 15 months",
      vaccine: "Varicella - Dose 1 of 2",
      protection: "Chickenpox",
      weeks: 52,
      months: 12,
      rangeMonths: 15,
    },
    {
      age: "12 to 23 months",
      vaccine: "Hepatitis A - Dose 1 of 2",
      protection: "Hepatitis A virus (inflammation of the liver)",
      weeks: 52,
      months: 12,
      rangeMonths: 23,
    },
    {
      age: "15 to 18 months",
      vaccine: "DTaP - Dose 4 of 5",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 65,
      months: 15,
      rangeMonths: 18,
    },
    {
      age: "18 months or older",
      vaccine: "Hepatitis A - Dose 2 of 2",
      protection: "Hepatitis A virus (inflammation of the liver)",
      weeks: 78,
      months: 18,
      note: "Follows 6 months after Dose 1",
    },
    {
      age: "4 to 6 years",
      vaccine: "DTaP - Dose 5 of 5",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 208,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4 to 6 years",
      vaccine: "Polio (IPV) - Dose 4 of 4",
      protection: "Polio",
      weeks: 208,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4 to 6 years",
      vaccine: "MMR - Dose 2 of 2",
      protection: "Measles, mumps, and rubella (German measles)",
      weeks: 208,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "4 to 6 years",
      vaccine: "Varicella - Dose 2 of 2",
      protection: "Chickenpox",
      weeks: 208,
      months: 48,
      rangeMonths: 72,
    },
    {
      age: "11 to 12 years",
      vaccine: "Tdap - Booster",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 572,
      months: 132,
      rangeMonths: 144,
      note: "Follows every 10 years after Dose 1",
    },
    {
      age: "11 to 12 years",
      vaccine: "MCV4 (Meningococcal) - Dose 1",
      protection: "Meningococcal conjugate vaccine",
      weeks: 572,
      months: 132,
      rangeMonths: 144,
    },
    {
      age: "11 to 12 years",
      vaccine: "HPV - Dose 1 of 3",
      protection: "Human Papillomavirus",
      weeks: 572,
      months: 132,
      rangeMonths: 144,
    },
    {
      age: "11 to 12 years",
      vaccine: "HPV - Dose 2 of 3",
      protection: "Human Papillomavirus",
      weeks: 572,
      months: 132,
      rangeMonths: 144,
      note: "Follows 1-2 months after Dose 1",
    },
    {
      age: "11 to 12 years",
      vaccine: "HPV - Dose 3 of 3",
      protection: "Human Papillomavirus",
      weeks: 572,
      months: 132,
      rangeMonths: 144,
      note: "Follows 4 months after Dose 2",
    },
  ],

  UK: [
    {
      age: "8 weeks (2 months)",
      vaccine: "6-in-1 Vaccine - Dose 1 of 3",
      protection:
        "Diphtheria, tetanus, pertussis (whooping cough), polio, Haemophilus influenzae type b (Hib) and hepatitis B",
      weeks: 8,
      months: 2,
    },
    {
      age: "8 weeks (2 months)",
      vaccine: "PCV - Dose 1 of 3",
      protection: "Pneumococcal conjugate vaccine (PCV)",
      weeks: 8,
      months: 2,
    },
    {
      age: "8 weeks (2 months)",
      vaccine: "Rotavirus - Dose 1 of 2",
      protection: "Rotavirus",
      weeks: 8,
      months: 2,
    },
    {
      age: "8 weeks (2 months)",
      vaccine: "MenB - Dose 1 of 3",
      protection: "Protects against type B meningococcal disease",
      weeks: 8,
      months: 2,
    },
    {
      age: "12 weeks (3 months)",
      vaccine: "6-in-1 Vaccine - Dose 2 of 3",
      protection:
        "Diphtheria, tetanus, pertussis (whooping cough), polio, Haemophilus influenzae type b (Hib) and hepatitis B",
      weeks: 12,
      months: 3,
    },
    {
      age: "12 weeks (3 months)",
      vaccine: "Rotavirus - Dose 2 of 2",
      protection: "Rotavirus",
      weeks: 12,
      months: 3,
    },
    {
      age: "16 weeks (4 months)",
      vaccine: "6-in-1 Vaccine - Dose 3 of 3",
      protection:
        "Diphtheria, tetanus, pertussis (whooping cough), polio, Haemophilus influenzae type b (Hib) and hepatitis B",
      weeks: 16,
      months: 4,
    },
    {
      age: "16 weeks (4 months)",
      vaccine: "PCV - Dose 2 of 3",
      protection: "Pneumococcal conjugate vaccine (PCV)",
      weeks: 16,
      months: 4,
    },
    {
      age: "16 weeks (4 months)",
      vaccine: "MenB - Dose 2 of 3",
      protection: "Protects against type B meningococcal disease",
      weeks: 16,
      months: 4,
    },
    {
      age: "12 to 13 months",
      vaccine: "Hib/MenC - Dose 1",
      protection: "Meningitis C / Haemophilus influenzae type b (Hib)",
      weeks: 52,
      months: 12,
      rangeMonths: 13,
    },
    {
      age: "12 to 13 months",
      vaccine: "PCV - Dose 3 of 3",
      protection: "Pneumococcal conjugate vaccine (PCV)",
      weeks: 52,
      months: 12,
      rangeMonths: 13,
    },
    {
      age: "12 to 13 months",
      vaccine: "MMR - Dose 1 of 2",
      protection: "Measles, mumps, and rubella (German measles)",
      weeks: 52,
      months: 12,
      rangeMonths: 13,
    },
    {
      age: "12 to 13 months",
      vaccine: "MenB - Dose 3 of 3",
      protection: "Protects against type B meningococcal disease",
      weeks: 52,
      months: 12,
      rangeMonths: 13,
    },
    {
      age: "2 to 8 years",
      vaccine: "Nasal Flu Vaccine (Annual)",
      protection: "An annual vaccine that protects against seasonal flu",
      weeks: 104,
      months: 24,
      rangeMonths: 96,
    },
    {
      age: "3 years 4 months",
      vaccine: "MMR - Dose 2 of 2",
      protection: "Measles, mumps, and rubella (German measles)",
      weeks: 173,
      months: 40,
    },
    {
      age: "3 years 4 months",
      vaccine: "4-in-1 Pre-school Booster",
      protection: "Diphtheria, tetanus, pertussis (whooping cough) and polio",
      weeks: 173,
      months: 40,
    },
    {
      age: "12 to 13 years",
      vaccine: "HPV - Dose 1 of 2",
      protection: "Human Papillomavirus",
      weeks: 624,
      months: 144,
      rangeMonths: 156,
    },
    {
      age: "12 to 13 years",
      vaccine: "HPV - Dose 2 of 2",
      protection: "Human Papillomavirus (6 months after Dose 1)",
      weeks: 624,
      months: 144,
      rangeMonths: 156,
      note: "Second dose follows 6 months after the first",
    },
    {
      age: "13 to 19 years",
      vaccine: "3-in-1 Teenage Booster",
      protection: "Tetanus, Diphtheria and Polio",
      weeks: 676,
      months: 156,
      rangeMonths: 228,
    },
    {
      age: "13 to 19 years",
      vaccine: "MenACWY - Dose 1",
      protection:
        "Protects against four different types of meningococcal disease (A, C, W, Y)",
      weeks: 676,
      months: 156,
      rangeMonths: 228,
    },
    {
      age: "65 years",
      vaccine: "Inactivated Flu Vaccine (Annual)",
      protection: "Protects against influenza (flu)",
      weeks: 3380,
      months: 780,
    },
    {
      age: "65 years",
      vaccine: "Shingles Vaccine - Dose 1",
      protection: "Protects against shingles",
      weeks: 3380,
      months: 780,
    },
    {
      age: "65 years",
      vaccine: "PPV - Dose 1",
      protection: "Pneumococcal polysaccharide vaccine (PPV)",
      weeks: 3380,
      months: 780,
    },
  ],

  AUSTRALIA: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1 of 4",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 0,
      months: 0,
    },
    {
      age: "2 months",
      vaccine: "6-in-1 - Dose 1 of 3 (Covers: DTPa, IPV, Hib, Hep B)",
      protection: "Diphtheria, tetanus, pertussis, polio, Hib, Hepatitis B",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Rotavirus - Dose 1 of 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "13vPCV - Dose 1 of 5",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 8,
      months: 2,
    },
    {
      age: "4 months",
      vaccine: "6-in-1 - Dose 2 of 3 (Covers: DTPa, IPV, Hib, Hep B)",
      protection: "Diphtheria, tetanus, pertussis, polio, Hib, Hepatitis B",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Rotavirus - Dose 2 of 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "13vPCV - Dose 2 of 5",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 17,
      months: 4,
    },
    {
      age: "6 months",
      vaccine: "6-in-1 - Dose 3 of 3 (Covers: DTPa, IPV, Hib, Hep B)",
      protection: "Diphtheria, tetanus, pertussis, polio, Hib, Hepatitis B",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Rotavirus - Dose 3 of 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "13vPCV - Dose 3 of 5",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 26,
      months: 6,
    },
    {
      age: "12 months",
      vaccine: "Hib - Dose 4 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 52,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "meningococcal C (MenC)",
      protection: "Meningococcal C",
      weeks: 52,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "MMR - Dose 1 of 2",
      protection: "Measles, mumps, and rubella",
      weeks: 52,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "13vPCV - Dose 4 of 5",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 52,
      months: 12,
    },
    {
      age: "12-18 months",
      vaccine: "13vPCV - Dose 5 of 5",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 52,
      months: 12,
      rangeMonths: 18,
    },
    {
      age: "18 months",
      vaccine: "MMR - Dose 2 of 2",
      protection: "Measles, mumps, and rubella",
      weeks: 78,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "Varicella - Dose 1 of 2",
      protection: "Chickenpox",
      weeks: 78,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "DTPa - Dose 4 of 6",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 78,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "IPV - Dose 4 of 5",
      protection: "Polio",
      weeks: 78,
      months: 18,
    },
    {
      age: "4 Years",
      vaccine: "4-in-1 - Booster (Covers: DTPa, IPV)",
      protection: "Diphtheria, tetanus, pertussis, polio",
      weeks: 208,
      months: 48,
    },
    {
      age: "4 Years",
      vaccine: "Pneumococcal vaccine (23vPPV) - Dose 1 of 2",
      protection: "For children with underlying medical conditions",
      weeks: 208,
      months: 48,
    },
    {
      age: "10-15 Years",
      vaccine: "Varicella - Dose 2 of 2",
      protection: "Chickenpox",
      weeks: 520,
      months: 120,
      rangeMonths: 180,
    },
    {
      age: "10-15 Years",
      vaccine: "HPV - Dose 1",
      protection: "Human Papillomavirus",
      weeks: 520,
      months: 120,
      rangeMonths: 180,
    },
    {
      age: "10-15 Years",
      vaccine: "DTPa - Dose 6 of 6",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 520,
      months: 120,
      rangeMonths: 180,
    },
    {
      age: "50 years and over",
      vaccine: "Pneumococcal vaccine (23vPPV) - Dose 2 of 2",
      protection: "For children with underlying medical conditions",
      weeks: 2600,
      months: 600,
    },
    {
      age: "50 years and over",
      vaccine: "Influenza (flu) - Every Year",
      protection: "Influenza Flu Vaccine",
      weeks: 2600,
      months: 600,
    },
  ],

  CANADA: [
    {
      age: "2 months",
      vaccine: "DTaP - Dose 1 of 7",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "IPV - Dose 1 of 5",
      protection: "Polio",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Hib - Dose 1 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Hepatitis B - Dose 1 of 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 8,
      months: 2,
    },
    {
      age: "4 months",
      vaccine: "DTaP - Dose 2 of 7",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "IPV - Dose 2 of 5",
      protection: "Polio",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Hib - Dose 2 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Hepatitis B - Dose 2 of 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "PNEU-C13 - Dose 1 of 3",
      protection: "Pneumococcal Disease",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Meningococcal conjugate (MenconC) - Dose 1 of 2",
      protection: "Meningococcal Disease",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Rotavirus - Dose 1 of 2",
      protection: "Rotavirus",
      weeks: 17,
      months: 4,
    },
    {
      age: "6 months",
      vaccine: "DTaP - Dose 3 of 7",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "IPV - Dose 3 of 5",
      protection: "Polio",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Hib - Dose 3 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Hepatitis B - Dose 3 of 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "PNEU-C13 - Dose 2 of 3",
      protection: "Pneumococcal Disease",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Rotavirus - Dose 2 of 2",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 26,
      months: 6,
    },
    {
      age: "12 months",
      vaccine: "MMR - Dose 1 of 2",
      protection: "Measles, mumps, and rubella",
      weeks: 52,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "Varicella - Dose 1 of 2",
      protection: "Chickenpox",
      weeks: 52,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "PNEU-C13 - Dose 3 of 3",
      protection: "Pneumococcal Disease",
      weeks: 52,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "Meningococcal conjugate (MenconC) - Dose 2 of 2",
      protection: "Meningococcal Disease",
      weeks: 52,
      months: 12,
    },
    {
      age: "18 months",
      vaccine: "DTaP - Dose 4 of 7",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 78,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "IPV - Dose 4 of 5",
      protection: "Polio",
      weeks: 78,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "Hib - Dose 4 of 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 78,
      months: 18,
    },
    {
      age: "4 years",
      vaccine: "DTaP - Dose 5 of 7",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 208,
      months: 48,
    },
    {
      age: "4 years",
      vaccine: "IPV - Dose 5 of 5",
      protection: "Polio",
      weeks: 208,
      months: 48,
    },
    {
      age: "4 years",
      vaccine: "MMR - Dose 2 of 2",
      protection: "Measles, mumps, and rubella",
      weeks: 208,
      months: 48,
    },
    {
      age: "4 years",
      vaccine: "Varicella - Dose 2 of 2",
      protection: "Chickenpox",
      weeks: 208,
      months: 48,
    },
    {
      age: "Grade 5",
      vaccine: "Hepatitis B - 3 Doses",
      protection: "Hepatitis B",
      weeks: 572,
      months: 132,
    },
    {
      age: "Grade 5",
      vaccine: "HPV - 3 Doses",
      protection: "Human papillomavirus",
      weeks: 572,
      months: 132,
    },
    {
      age: "Grade 9",
      vaccine: "DTaP - Dose 6 of 7",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 748,
      months: 172,
    },
    {
      age: "Grade 9",
      vaccine: "MenC-ACYW - Dose 1",
      protection: "Meningococcal Conjugate Vaccine (Groups A, C, W-135 and Y)",
      weeks: 748,
      months: 172,
    },
    {
      age: "Grade 9",
      vaccine: "HPV - 3 Doses",
      protection: "Human papillomavirus",
      weeks: 748,
      months: 172,
    },
    {
      age: "Adult",
      vaccine: "Td (every 10 years)",
      protection: "Tetanus, diphtheria",
      weeks: 0,
      months: 216,
    },
    {
      age: "Adult",
      vaccine: "DTaP - Dose 7 of 7",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 0,
      months: 216,
    },
    {
      age: "65 years",
      vaccine: "PNEUMO-P - Dose 1",
      protection: "Pneumococcal polysaccharide",
      weeks: 3380,
      months: 780,
    },
  ],

  KUWAIT: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 0,
      months: 0,
    },
    {
      age: "2 months",
      vaccine: "Pentavalent - Dose 1 of 4",
      protection: "Hepatitis B, Diphtheria, Tetanus, Pertussis, Hib",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Polio (IPV) - Dose 1",
      protection: "Polio",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "PCV - Dose 1 of 4",
      protection:
        "Pneumonia (chest infection), ear infections and meningitis (a brain infection)",
      weeks: 8,
      months: 2,
    },
    {
      age: "3 months",
      vaccine: "BCG - Dose 1",
      protection: "Bacillus Calmette–Guerin (Protection against tuberculosis)",
      weeks: 13,
      months: 3,
    },
    {
      age: "4 months",
      vaccine: "Pentavalent - Dose 2 of 4",
      protection: "Hepatitis B, Diphtheria, Tetanus, Pertussis, Hib",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "PCV - Dose 2 of 4",
      protection:
        "Pneumonia (chest infection), ear infections and meningitis (a brain infection)",
      weeks: 17,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "OPV - Dose 1 of 5",
      protection: "Oral Polio Vaccine",
      weeks: 17,
      months: 4,
    },
    {
      age: "6 months",
      vaccine: "Pentavalent - Dose 3 of 4",
      protection: "Hepatitis B, Diphtheria, Tetanus, Pertussis, Hib",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "PCV - Dose 3 of 4",
      protection:
        "Pneumonia (chest infection), ear infections and meningitis (a brain infection)",
      weeks: 26,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "OPV - Dose 2 of 5",
      protection: "Oral Polio Vaccine",
      weeks: 26,
      months: 6,
    },
    {
      age: "1 Year",
      vaccine: "MMR - Dose 1 of 3",
      protection: "Measles, mumps, and rubella",
      weeks: 52,
      months: 12,
    },
    {
      age: "1 Year",
      vaccine: "OPV - Dose 3 of 5",
      protection: "Oral Polio Vaccine",
      weeks: 52,
      months: 12,
    },
    {
      age: "18 months",
      vaccine: "OPV - Dose 4 of 5",
      protection: "Oral Polio Vaccine",
      weeks: 78,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "Pentavalent Booster - Dose 4 of 4",
      protection: "Hepatitis B, Diphtheria, Tetanus, Pertussis, Hib",
      weeks: 78,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "PCV Booster - Dose 4 of 4",
      protection:
        "Pneumonia (chest infection), ear infections and meningitis (a brain infection)",
      weeks: 78,
      months: 18,
    },
    {
      age: "2 Years",
      vaccine: "MenC-ACYW - Dose 1",
      protection: "Meningococcal Conjugate Vaccine (Groups A, C, W-135 and Y)",
      weeks: 104,
      months: 24,
    },
    {
      age: "2 Years",
      vaccine: "MMR Booster - Dose 2 of 3",
      protection: "Measles, mumps, and rubella",
      weeks: 104,
      months: 24,
    },
    {
      age: "3.5 Years",
      vaccine: "OPV Booster - Dose 5 of 5",
      protection: "Oral Polio Vaccine",
      weeks: 182,
      months: 42,
    },
    {
      age: "3.5 Years",
      vaccine: "DTaP Booster - Dose 1",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 182,
      months: 42,
    },
    {
      age: "10-12 Years",
      vaccine: "MMR Booster (Girls) - Dose 3 of 3",
      protection: "Measles, mumps, and rubella",
      weeks: 520,
      months: 120,
      rangeMonths: 144,
    },
    {
      age: "10-12 Years",
      vaccine: "Td - Dose 1 of 2",
      protection: "Tetanus, Diphtheria",
      weeks: 520,
      months: 120,
      rangeMonths: 144,
    },
    {
      age: "16-18 Years",
      vaccine: "Td - Dose 2 of 2",
      protection: "Tetanus, Diphtheria",
      weeks: 832,
      months: 192,
      rangeMonths: 216,
    },
  ],

  MALAYSIA: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 0,
      months: 0,
    },
    {
      age: "At Birth",
      vaccine: "BCG - Dose 1",
      protection:
        "Bacillus Calmette–Guerin (Protection against Tuberculosis & Bladder Cancer)",
      weeks: 0,
      months: 0,
    },
    {
      age: "1 month",
      vaccine: "Hepatitis B - Dose 2",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 4,
      months: 1,
    },
    {
      age: "2 months",
      vaccine: "DTaP - Dose 1",
      protection: "Diphtheria, Tetanus and accellular Pertussis",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Hib - Dose 1",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "IPV - Dose 1",
      protection: "Polio",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Rotavirus - Dose 1",
      protection: "Rotavirus (Optional)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "PCV - Dose 1",
      protection: "Pneumococcal conjugate vaccine (PCV) (Optional)",
      weeks: 8,
      months: 2,
    },
    {
      age: "3 months",
      vaccine: "DTaP - Dose 2",
      protection: "Diphtheria, Tetanus and accellular Pertussis",
      weeks: 12,
      months: 3,
    },
    {
      age: "3 months",
      vaccine: "Hib - Dose 2",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 12,
      months: 3,
    },
    {
      age: "3 months",
      vaccine: "IPV - Dose 2",
      protection: "Polio",
      weeks: 12,
      months: 3,
    },
    {
      age: "5 months",
      vaccine: "DTaP - Dose 3",
      protection: "Diphtheria, Tetanus and accellular Pertussis",
      weeks: 20,
      months: 5,
    },
    {
      age: "5 months",
      vaccine: "Hib - Dose 3",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 20,
      months: 5,
    },
    {
      age: "5 months",
      vaccine: "IPV - Dose 3",
      protection: "Polio",
      weeks: 20,
      months: 5,
    },
    {
      age: "6 months",
      vaccine: "Hepatitis B - Dose 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 24,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Measles - Dose 1",
      protection: "Measles (Sabah Only)",
      weeks: 24,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Influenza - Dose 1",
      protection: "Influenza (optional)",
      weeks: 24,
      months: 6,
    },
    {
      age: "10 months",
      vaccine: "JE - Dose 1",
      protection: "Japanese Encephalitis (JE) (Sarawak Only)",
      weeks: 40,
      months: 10,
    },
    {
      age: "10 months",
      vaccine: "Hepatitis A - Dose 1",
      protection: "Hepatitis A virus (inflammation of the liver) (Optional)",
      weeks: 40,
      months: 10,
    },
    {
      age: "12 months",
      vaccine: "MMR - Dose 1",
      protection: "Measles, Mumps, and Rubella",
      weeks: 48,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "JE - Dose 2",
      protection: "Japanese Encephalitis (JE) (Sarawak Only)",
      weeks: 48,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "Chicken Pox - Dose 1",
      protection: "Chicken Pox (Optional)",
      weeks: 48,
      months: 12,
    },
    {
      age: "18 months",
      vaccine: "DTaP - Dose 4",
      protection: "Diphtheria, Tetanus and accellular Pertussis",
      weeks: 72,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "Hib - Dose 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 72,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "IPV - Dose 4",
      protection: "Polio",
      weeks: 72,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "JE - Dose 3",
      protection: "Japanese Encephalitis (JE) (Sarawak Only)",
      weeks: 72,
      months: 18,
    },
    {
      age: "4 years",
      vaccine: "JE - Dose 4",
      protection: "Japanese Encephalitis (JE) (Sarawak Only)",
      weeks: 208,
      months: 48,
    },
    {
      age: "7 Years",
      vaccine: "BCG - Dose 2",
      protection:
        "Bacillus Calmette–Guerin (Protection against Tuberculosis & Bladder Cancer)",
      weeks: 364,
      months: 84,
    },
    {
      age: "7 Years",
      vaccine: "DT Booster - Dose 1",
      protection: "Diptheria, Tetanus Booster",
      weeks: 364,
      months: 84,
    },
    {
      age: "7 Years",
      vaccine: "MMR - Dose 2",
      protection: "Measles, Mumps, and Rubella",
      weeks: 364,
      months: 84,
    },
    {
      age: "13 Years",
      vaccine: "HPV - Dose 1",
      protection: "Human Papillomavirus",
      weeks: 676,
      months: 156,
    },
    {
      age: "13 Years",
      vaccine: "HPV - Dose 2",
      protection: "Human Papillomavirus",
      weeks: 680,
      months: 157,
    },
    {
      age: "13 Years",
      vaccine: "HPV - Dose 3",
      protection: "Human Papillomavirus",
      weeks: 704,
      months: 162,
    },
    {
      age: "15 Years",
      vaccine: "TT - Dose 1",
      protection: "Tetanus",
      weeks: 780,
      months: 180,
    },
  ],

  NIGERIA: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 0,
      months: 0,
    },
    {
      age: "At Birth",
      vaccine: "BCG - Dose 1",
      protection:
        "Bacillus Calmette–Guerin (Protection against tuberculosis & Bladder Cancer)",
      weeks: 0,
      months: 0,
    },
    {
      age: "At Birth",
      vaccine: "OPV - Dose 1",
      protection: "Polio",
      weeks: 0,
      months: 0,
    },
    {
      age: "6 weeks",
      vaccine: "Pentavalent - Dose 1",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications) Diphtheria, tetanus and pertussis (whooping cough) Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 weeks",
      vaccine: "Rotavirus - Dose 1",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 weeks",
      vaccine: "PCV - Dose 1",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 weeks",
      vaccine: "OPV - Dose 2",
      protection: "Polio",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "10 weeks",
      vaccine: "Pentavalent - Dose 2",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications) Diphtheria, tetanus and pertussis (whooping cough) Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 10,
      months: 2.5,
    },
    {
      age: "10 weeks",
      vaccine: "Rotavirus - Dose 2",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 10,
      months: 2.5,
    },
    {
      age: "10 weeks",
      vaccine: "PCV - Dose 2",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 10,
      months: 2.5,
    },
    {
      age: "10 weeks",
      vaccine: "OPV - Dose 3",
      protection: "Polio",
      weeks: 10,
      months: 2.5,
    },
    {
      age: "14 weeks",
      vaccine: "Pentavalent - Dose 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications) Diphtheria, tetanus and pertussis (whooping cough) Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "14 weeks",
      vaccine: "PCV - Dose 3",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "14 weeks",
      vaccine: "OPV - Dose 4",
      protection: "Polio",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "6 months",
      vaccine: "Vitamin A - Dose 1",
      protection: "Vitamin A dificiency",
      weeks: 24,
      months: 6,
    },
    {
      age: "9 months",
      vaccine: "Measles - Dose 1",
      protection: "Measles Vaccine",
      weeks: 36,
      months: 9,
    },
    {
      age: "9 months",
      vaccine: "Yellow Fever - Dose 1",
      protection: "Yellow Fever Vaccine",
      weeks: 36,
      months: 9,
    },
    {
      age: "12-24 months",
      vaccine: "Meningitis - Dose 1",
      protection: "Meningitis & Septicaemia",
      weeks: 52,
      months: 12,
    },
    {
      age: "12-24 months",
      vaccine: "Vitamin A - Dose 2",
      protection: "Vitamin A dificiency",
      weeks: 52,
      months: 12,
    },
    {
      age: "12-24 months",
      vaccine: "OPV Booster - Dose 5",
      protection: "Polio",
      weeks: 52,
      months: 12,
    },
    {
      age: "15-18 months",
      vaccine: "MMR (Priorix) - Dose 1",
      protection: "Measles, mumps, and rubella (German measles)",
      weeks: 60,
      months: 15,
    },
    {
      age: "15-18 months",
      vaccine: "Varicella (varilrix) - Dose 1",
      protection: "Chickenpox",
      weeks: 60,
      months: 15,
    },
    {
      age: "24 months",
      vaccine: "Typhoid Conjugate Vaccine - Dose 1",
      protection: "Typhoid fever",
      weeks: 104,
      months: 24,
    },
    {
      age: "13 years",
      vaccine: "HPV (Cervarix) - Dose 1",
      protection: "Cervical Cancer caused by Human Papilloma Virus (HPV)",
      weeks: 676,
      months: 156,
    },
  ],

  QATAR: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 0,
      months: 0,
    },
    {
      age: "At Birth",
      vaccine: "BCG - Dose 1",
      protection: "Bacillus Calmette–Guerin (Protection against tuberculosis)",
      weeks: 0,
      months: 0,
    },
    {
      age: "2 months",
      vaccine: "BCG - Dose 1",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications) Diphtheria, tetanus and pertussis (whooping cough) Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Polio - Dose 1",
      protection: "Polio",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Pentavalent - Dose 1",
      protection:
        "protects against pneumonia (chest infection), ear infections and meningitis (a brain infection)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "PCV - Dose 1",
      protection: "Meningococcal Conjugate Vaccine (Groups A, C, W-135 and Y)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Rotavirus - Dose 1",
      protection: "Rotavirus diarrhea",
      weeks: 8,
      months: 2,
    },
    {
      age: "4 months",
      vaccine: "MenC-ACYW - Dose 1",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications) Diphtheria, tetanus and pertussis (whooping cough) Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 16,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "PCV - Dose 2",
      protection:
        "protects against pneumonia (chest infection), ear infections and meningitis (a brain infection)",
      weeks: 16,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Pentavalent - Dose 2",
      protection: "Rotavirus diarrhea",
      weeks: 16,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Rotavirus - Dose 2",
      protection: "Oral Polio Vaccine",
      weeks: 16,
      months: 4,
    },
    {
      age: "6 months",
      vaccine: "OPV - Dose 1",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications) Diphtheria, tetanus and pertussis (whooping cough) Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 24,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "PCV - Dose 3",
      protection:
        "protects against pneumonia (chest infection), ear infections and meningitis (a brain infection)",
      weeks: 24,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Pentavalent - Dose 3",
      protection: "Oral Polio Vaccine",
      weeks: 24,
      months: 6,
    },
    {
      age: "12 months",
      vaccine: "OPV - Dose 2",
      protection: "Measles, mumps, and rubella",
      weeks: 52,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "Varicella - Dose 1",
      protection: "Chickenpox",
      weeks: 52,
      months: 12,
    },
    {
      age: "12 months",
      vaccine: "MMR - Dose 1",
      protection: "Hepatitis A virus (inflammation of the liver)",
      weeks: 52,
      months: 12,
    },
    {
      age: "15 months",
      vaccine: "Hepatitis A - Dose 1",
      protection:
        "protects against pneumonia (chest infection), ear infections and meningitis (a brain infection)",
      weeks: 65,
      months: 15,
    },
    {
      age: "15 months",
      vaccine: "PCV Booster - Dose 4",
      protection: "Meningococcal Conjugate Vaccine",
      weeks: 65,
      months: 15,
    },
    {
      age: "18 months",
      vaccine: "MMR - Dose 2",
      protection: "Measles, mumps, and rubella",
      weeks: 78,
      months: 18,
    },
    {
      age: "18 months",
      vaccine: "OPV Booster - Dose 3",
      protection: "Oral Polio Vaccine",
      weeks: 78,
      months: 18,
    },
    {
      age: "24 months",
      vaccine: "Hepatitis A - Dose 2",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 104,
      months: 24,
    },
    {
      age: "3-4 Years",
      vaccine: "Hepatitis B - Dose 2",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 156,
      months: 36,
    },
    {
      age: "3-4 Years",
      vaccine: "Varicella - Dose 2",
      protection: "Chickenpox",
      weeks: 156,
      months: 36,
    },
    {
      age: "4-6 Years",
      vaccine: "DTaP - Dose 1",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 208,
      months: 48,
    },
    {
      age: "4-6 Years",
      vaccine: "Hepatitis B - Dose 4",
      protection: "Oral Polio Vaccine",
      weeks: 208,
      months: 48,
    },
    {
      age: "11-12 Years",
      vaccine: "OPV Booster - Dose 4",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 572,
      months: 132,
    },
    {
      age: "13-16 Years",
      vaccine: "Hepatitis B - Dose 5",
      protection: "Tetanus, diphtheria, and pertussis",
      weeks: 676,
      months: 156,
    },
  ],

  SOUTH_AFRICA: [
    {
      age: "Birth",
      vaccine: "TOPV - Dose 1",
      protection: "Trivalent Oral Polio Vaccine",
      weeks: 0,
      months: 0,
    },
    {
      age: "Birth",
      vaccine: "BCG - Dose 1",
      protection: "Bacillus Calmette–Guerin (Protection against tuberculosis)",
      weeks: 0,
      months: 0,
    },
    {
      age: "6 Weeks",
      vaccine: "TOPV - Dose 2",
      protection: "Trivalent Oral Polio Vaccine",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 Weeks",
      vaccine: "Rotavirus - Dose 1",
      protection: "Rotavirus",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 Weeks",
      vaccine: "PCV - Dose 1",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 Weeks",
      vaccine: "Pentaxim - Dose 1",
      protection:
        "Diphtheria, tetanus and pertussis (whooping cough) Infections of the blood, brain, joints, or lungs (pneumonia) Polio",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "6 Weeks",
      vaccine: "Hepatitis B - Dose 1",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 6,
      months: 1.5,
    },
    {
      age: "10 Weeks",
      vaccine: "Pentaxim - Dose 2",
      protection:
        "Diphtheria, tetanus and pertussis (whooping cough) Infections of the blood, brain, joints, or lungs (pneumonia) Polio",
      weeks: 10,
      months: 2.5,
    },
    {
      age: "10 Weeks",
      vaccine: "Hepatitis B - Dose 2",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 10,
      months: 2.5,
    },
    {
      age: "14 Weeks",
      vaccine: "Rotavirus - Dose 2",
      protection: "Rotavirus",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "14 Weeks",
      vaccine: "PCV - Dose 2",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "14 Weeks",
      vaccine: "Pentaxim - Dose 3",
      protection:
        "Diphtheria, tetanus and pertussis (whooping cough) Infections of the blood, brain, joints, or lungs (pneumonia) Polio",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "14 Weeks",
      vaccine: "Hepatitis B - Dose 3",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 14,
      months: 3.5,
    },
    {
      age: "6/9 Months",
      vaccine: "Measles - Dose 1",
      protection: "Measles",
      weeks: 24,
      months: 6,
    },
    {
      age: "9 months",
      vaccine: "PCV - Dose 3",
      protection: "Pneumococcal conjugate Vaccine",
      weeks: 36,
      months: 9,
    },
    {
      age: "12-18 Months",
      vaccine: "Measles - Dose 2",
      protection: "Measles",
      weeks: 52,
      months: 12,
    },
    {
      age: "18 months",
      vaccine: "Pentaxim - Dose 4",
      protection:
        "Diphtheria, tetanus and pertussis (whooping cough) Infections of the blood, brain, joints, or lungs (pneumonia) Polio",
      weeks: 78,
      months: 18,
    },
    {
      age: "6 years",
      vaccine: "Td - Dose 1",
      protection: "Diftavax (Tetanus, Diptheria)",
      weeks: 312,
      months: 72,
    },
    {
      age: "9 Years",
      vaccine: "HPV (girls) - Dose 1",
      protection: "Human papilloma Virus",
      weeks: 468,
      months: 108,
    },
    {
      age: "9.5 Years",
      vaccine: "HPV (girls) - Dose 2",
      protection: "Human papilloma Virus",
      weeks: 494,
      months: 114,
    },
    {
      age: "12 years",
      vaccine: "Td - Dose 2",
      protection: "Diftavax (Tetanus, Diptheria)",
      weeks: 624,
      months: 144,
    },
  ],

  OTHERS: [
    {
      age: "At Birth",
      vaccine: "Hepatitis B - Dose 1",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 0,
      months: 0,
    },
    {
      age: "1-2 months",
      vaccine: "Hepatitis B - Dose 2",
      protection:
        "Hepatitis B virus (chronic inflammation of the liver, life-long complications)",
      weeks: 4,
      months: 1,
    },
    {
      age: "2 months",
      vaccine: "DTaP - Dose 1",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Hib - Dose 1",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Polio (IPV) - Dose 1",
      protection: "Polio",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Pneumococcal conjugate (PCV13) - Dose 1",
      protection:
        "Infections of the blood, brain, joints, inner ears, or lungs (pneumonia)",
      weeks: 8,
      months: 2,
    },
    {
      age: "2 months",
      vaccine: "Rotavirus - Dose 1",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 8,
      months: 2,
    },
    {
      age: "4 months",
      vaccine: "DTaP - Dose 2",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 16,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Hib - Dose 2",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 16,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Polio (IPV) - Dose 2",
      protection: "Polio",
      weeks: 16,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Pneumococcal conjugate (PCV13) - Dose 2",
      protection:
        "Infections of the blood, brain, joints, inner ears, or lungs (pneumonia)",
      weeks: 16,
      months: 4,
    },
    {
      age: "4 months",
      vaccine: "Rotavirus - Dose 2",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 16,
      months: 4,
    },
    {
      age: "6 months",
      vaccine: "DTaP - Dose 3",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 24,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Hib - Dose 3",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 24,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Pneumococcal conjugate (PCV13) - Dose 3",
      protection:
        "Infections of the blood, brain, joints, inner ears, or lungs (pneumonia)",
      weeks: 24,
      months: 6,
    },
    {
      age: "6 months",
      vaccine: "Rotavirus - Dose 3",
      protection: "Rotavirus diarrhea (and vomiting)",
      weeks: 24,
      months: 6,
    },
    {
      age: "6-18 months",
      vaccine: "Hepatitis B - Dose 3",
      protection:
        "Hepatitis B (chronic inflammation of the liver, life-long complications)",
      weeks: 24,
      months: 6,
    },
    {
      age: "6-18 months",
      vaccine: "Polio (IPV) - Dose 3",
      protection: "Polio",
      weeks: 24,
      months: 6,
    },
    {
      age: "6 months or older",
      vaccine: "Influenza - Dose 1",
      protection: "Flu and complications",
      weeks: 24,
      months: 6,
    },
    {
      age: "6 months or older",
      vaccine: "Influenza - Dose 2",
      protection: "Flu and complications",
      weeks: 28,
      months: 7,
    },
    {
      age: "12-15 months",
      vaccine: "Hib - Dose 4",
      protection:
        "Infections of the blood, brain, joints, or lungs (pneumonia)",
      weeks: 52,
      months: 12,
    },
    {
      age: "12-15 months",
      vaccine: "Pneumococcal conjugate (PCV13) - Dose 4",
      protection:
        "Infections of the blood, brain, joints, inner ears, or lungs (pneumonia)",
      weeks: 52,
      months: 12,
    },
    {
      age: "12-15 months",
      vaccine: "MMR - Dose 1",
      protection: "Measles, mumps, and rubella (German measles)",
      weeks: 52,
      months: 12,
    },
    {
      age: "12-15 months",
      vaccine: "Varicella - Dose 1",
      protection: "Chickenpox",
      weeks: 52,
      months: 12,
    },
    {
      age: "12-23 months",
      vaccine: "Hepatitis A - Dose 1",
      protection: "Hepatitis A virus (inflammation of the liver)",
      weeks: 52,
      months: 12,
    },
    {
      age: "15-18 months",
      vaccine: "DTaP - Dose 4",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 65,
      months: 15,
    },
    {
      age: "18 months or older",
      vaccine: "Hepatitis A - Dose 2",
      protection: "Hepatitis A virus (inflammation of the liver)",
      weeks: 78,
      months: 18,
    },
    {
      age: "4-6 years",
      vaccine: "DTaP - Dose 5",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 208,
      months: 48,
    },
    {
      age: "4-6 years",
      vaccine: "Polio (IPV) - Dose 4",
      protection: "Polio",
      weeks: 208,
      months: 48,
    },
    {
      age: "4-6 years",
      vaccine: "MMR - Dose 2",
      protection: "Measles, mumps, and rubella (German measles)",
      weeks: 208,
      months: 48,
    },
    {
      age: "4-6 years",
      vaccine: "Varicella - Dose 2",
      protection: "Chickenpox",
      weeks: 208,
      months: 48,
    },
    {
      age: "11-12 years",
      vaccine: "Tdap - Dose 1",
      protection: "Diphtheria, tetanus and pertussis (whooping cough)",
      weeks: 572,
      months: 132,
    },
    {
      age: "11-12 years",
      vaccine: "MCV4 - Dose 1",
      protection: "Meningococcal conjugate vaccine",
      weeks: 572,
      months: 132,
    },
    {
      age: "11-12 years",
      vaccine: "HPV - Dose 1",
      protection: "Human Papillomavirus",
      weeks: 572,
      months: 132,
    },
    {
      age: "11-12 years",
      vaccine: "HPV - Dose 2",
      protection: "Human Papillomavirus",
      weeks: 576,
      months: 133,
    },
    {
      age: "11-12 years",
      vaccine: "HPV - Dose 3",
      protection: "Human Papillomavirus",
      weeks: 600,
      months: 138,
    },
  ],
};

export default immunizationSchedules;
